협상 history tab 컴포넌트 추가
Your-Planet/front-end pull request #290
Opened 2024-10-12 06:07 UTC by naeunchan

![image](https://github.com/user-attachments/assets/3f45d4a3-f982-4e2d-8eb6-739f4de5fb1d)

project/[id]/details 페이지 추가

2024-10-12 06:07 UTC, naeunchan commented
마땅한 mui component가 없어서 button으로 했음

2024-10-13 03:02 UTC, hyeonQyu commented
클릭 이벤트가 없는 버튼을 단순히 모양 때문에 사용하는거는 웹 접근성에서 낮은 점수를 받게 되고 검색 엔진 최적화(SEO)에도 나쁜 영향을 미치기 때문에 지양해야하는 부분임
Chip 컴포넌트의 모양을 변경해서 사용하는것이 더 적절해보임

추가로 탭이라는 이름 역시 클릭해서 페이지를 네비게이팅하는 역할이 있는 이름인데 여기서는 단순히 진행상황을 표시하는 역할만 하기 때문에 이름이 적절하지 않아
탭보다는 스텝바, 프로세스바 같은 이름이 더 맞을거같음

2024-10-13 03:02 UTC, hyeonQyu requested changes
클릭 이벤트가 없는 버튼을 단순히 모양 때문에 사용하는거는 웹 접근성에서 낮은 점수를 받게 되고 검색 엔진 최적화(SEO)에도 나쁜 영향을 미치기 때문에 지양해야하는 부분임
Chip 컴포넌트의 모양을 변경해서 사용하는것이 더 적절해보임

추가로 탭이라는 이름 역시 클릭해서 페이지를 네비게이팅하는 역할이 있는 이름인데 여기서는 단순히 진행상황을 표시하는 역할만 하기 때문에 이름이 적절하지 않아
탭보다는 스텝바, 프로세스바 같은 이름이 더 맞을거같음

2024-10-13 03:04 UTC, hyeonQyu commented on src/components/project/components/NegotiationHistoryTab/NegotiationHistoryTabs/index.tsx
> +						variant={currentNegotiationProgress === negotiationProgress ? "contained" : "outlined"}
이 컴포넌트의 추상화 레벨로 봤을때는 variant로 받기보다 현재 선택되었는지 여부로 받는게 맞아보임

2024-10-13 11:27 UTC, naeunchan commented on src/components/project/components/NegotiationHistoryTab/NegotiationHistoryTabs/index.tsx
> +						variant={currentNegotiationProgress === negotiationProgress ? "contained" : "outlined"}
done

확인부탁

2024-10-21 13:56 UTC, hyeonQyu approved these changes

2024-10-22 12:43 UTC, merged