프로젝트 상태 chip 추가
Your-Planet/front-end pull request #293
Opened 2024-10-13 12:10 UTC by naeunchan

![image](https://github.com/user-attachments/assets/d4322b51-f05b-497a-bf75-2625d7ad554f)

코멘트 해준 대로 상태에 따라 라벨이랑 색 알아서 매칭되게 해봤음

2024-10-21 14:05 UTC, hyeonQyu requested changes

2024-10-21 14:05 UTC, hyeonQyu commented on src/defines/forms/project/types/project.types.details.ts
> +export type ColorType = "error" | "info" | "primary" | "success" | "default" | "secondary" | "warning";
이 ColorType이 MUI 전체에서 사용되는 색인것 같아서 여기 말고 프로젝트 전체의 defines에 작성되는게 좋을거같음

2024-10-22 12:51 UTC, naeunchan commented on src/defines/forms/project/types/project.types.details.ts
> +export type ColorType = "error" | "info" | "primary" | "success" | "default" | "secondary" | "warning";
done
/defines/common/types.ts 파일 만들어서 추가

2024-10-22 12:51 UTC, naeunchan commented on src/defines/forms/project/constants/project.constants.details.ts
> +});
done

2024-10-26 14:15 UTC, hyeonQyu approved these changes

2024-10-27 03:17 UTC, merged