크리에이터 자세히보기/ 프로젝트 의뢰 버튼 click event 추가
Your-Planet/front-end pull request #294
Opened 2024-10-20 05:55 UTC by naeunchan

크리에이터 검색 화면에서 자세히보기 및 프로젝트 의뢰하기 버튼 이벤트 추가

2024-10-21 14:03 UTC, hyeonQyu commented
이거 main 브랜치 바라보는 상태에서 이렇게 옮기면
https://github.com/Your-Planet/front-end/pull/292
이쪽이랑 충돌날거같은데

2024-10-21 14:06 UTC, hyeonQyu requested changes
이거 main 브랜치 바라보는 상태에서 이렇게 옮기면
https://github.com/Your-Planet/front-end/pull/292
이쪽이랑 충돌날거같은데

타겟 브랜치 저쪽으로 옮겨야할거같음

2024-10-25 13:27 UTC, naeunchan commented
왜 /creators/[id] 하면 안불러와지지

2024-10-26 14:16 UTC, hyeonQyu commented
> 왜 /creators/[id] 하면 안불러와지지

오류 수정한 PR 올림

2024-10-26 14:16 UTC, hyeonQyu approved these changes

2024-10-27 03:21 UTC, merged